PKG_NAME="vulkan-headers"
PKG_VERSION="cfebfc96b2b0bce93da7d12f2c14cc01793ae25c"
PKG_LICENSE="Apache 2.0"
PKG_SITE="https://github.com/KhronosGroup/Vulkan-Headers"
PKG_URL="${PKG_SITE}.git"
PKG_DEPENDS_TARGET="toolchain cmake:host Python3"
PKG_LONGDESC="Vulkan Installable Client Driver (ICD) Loader."
